#:schema https://docs.jj-vcs.dev/latest/config-schema.json

[ui]
default-command = "log"

[user]
name = "Logan Collins"
email = "logan.collins@vanta.com"

[aliases]
tug = ["bookmark", "move", "--from", "heads(::@- & bookmarks())", "--to", "@-"]